---
- name: Install Oracle DB
  hosts: all
  become: yes
  tasks:
    - name: Copy rpm file to server
      copy:
       src: package.rpm
       dest: /tmp/package.rpm
       
    - name: Download Database PreInstall
      get_url: 
       url: https://yum.oracle.com/repo/OracleLinux/OL8/developer/x86_64/getPackage/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm 
       dest: ~/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm

    - name: Download Database Install
      get_url: 
       url: https://download.oracle.com/otn-pub/otn_software/db-free/oracle-database-free-23c-1.0-1.el8.x86_64.rpm
       dest: ~/oracle-database-free-23c-1.0-1.el8.x86_64.rpm


#    - name: Install package.
#      yum:
#       name: /tmp/package.rpm
#       state: present
