---
- name: Install Oracle DB
  hosts: all
  become: yes
  tasks:
  
    - name: Create a download directory if it does not exist
      file:
       path: ~/dl
       state: directory
       mode: '0755'
       
    - name: Copy SQLPlus to Server
      copy:
       src: oracle-instantclient-sqlplus-21.11.0.0.0-1.el8.x86_64.rpm
       dest: ~/dl/oracle-instantclient-sqlplus-21.11.0.0.0-1.el8.x86_64.rpm
       
    - name: Download Database PreInstall
      get_url: 
       url: https://yum.oracle.com/repo/OracleLinux/OL8/developer/x86_64/getPackage/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm 
       dest: ~/dl/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm

    - name: Download Database Install
      get_url: 
       url: https://download.oracle.com/otn-pub/otn_software/db-free/oracle-database-free-23c-1.0-1.el8.x86_64.rpm
       dest: ~/dl/oracle-database-free-23c-1.0-1.el8.x86_64.rpm

    - name: Download Instantclient
      get_url: 
       url: https://download.oracle.com/otn_software/linux/instantclient/2111000/oracle-instantclient-basic-21.11.0.0.0-1.el8.x86_64.rpm
       dest: ~/dl/oracle-instantclient-basic-21.11.0.0.0-1.el8.x86_64.rpm

    - name: Install Instantclient
      yum:
       name: ~/dl/oracle-instantclient-basic-21.11.0.0.0-1.el8.x86_64.rpm
       state: present
      register: cmd_output

    - ansible.builtin.debug:
        var: cmd_output

    - name: Install SQLPlus
      yum:
       name: ~/dl/oracle-instantclient-sqlplus-21.11.0.0.0-1.el8.x86_64.rpm
       state: present
      register: cmd_output

    - ansible.builtin.debug:
        var: cmd_output

    - name:  Run Oracle Preinstall
      yum:
       name: ~/dl/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm
       state: present
      register: cmd_output

    - ansible.builtin.debug:
        var: cmd_output

    - name: Install Database
      yum:
       name: ~/dl/oracle-database-free-23c-1.0-1.el8.x86_64.rpm
       state: present
      register: cmd_output

    - ansible.builtin.debug:
        var: cmd_output

#    - name: Install package.
#      yum:
#       name: /tmp/package.rpm
#       state: present
